title: "syyc_ blog"
description: "A minimal blog built with GitHub Pages"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Add this line
include:
  - assets/css/custom.css

# Add this too
defaults:
  - scope:
      path: ""
    values:
      head: head-custom.html
